-- Studia 3.0 Supabase SQL Schema
-- Run this script in the Supabase SQL Editor to initialize the database

-- 1. Create custom enum types
CREATE TYPE goal_type AS ENUM ('study', 'health', 'work', 'other');
CREATE TYPE session_status AS ENUM ('pending', 'completed', 'missed');
CREATE TYPE mechanic_type AS ENUM ('theory', 'quiz', 'flashcard', 'mock');

-- 2. Create the Users table
-- Extends the auth.users table using Supabase triggers
CREATE TABLE public.users (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  display_name TEXT,
  study_tone TEXT DEFAULT 'Sócrates Motivador',
  preferred_mechanics TEXT[] DEFAULT ARRAY['flashcards', 'quiz', 'theory'],
  points INTEGER DEFAULT 0,
  level INTEGER DEFAULT 1,
  current_streak INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);

-- Note: RLS (Row Level Security) ensuring users can only read/write their own data
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view their own profile." ON public.users FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Users can update their own profile." ON public.users FOR UPDATE USING (auth.uid() = id);

-- Trigger to automatically create a row in public.users when a new auth.users signs up
CREATE OR REPLACE FUNCTION public.handle_new_user() 
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.users (id, display_name)
  VALUES (NEW.id, NEW.email);
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- 3. Create the Goals table
CREATE TABLE public.goals (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
  title TEXT NOT NULL,
  type goal_type DEFAULT 'study',
  color_hex TEXT DEFAULT '#8DB600',
  status TEXT DEFAULT 'active',
  target_date TIMESTAMP WITH TIME ZONE,
  progress INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);

ALTER TABLE public.goals ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can manage their own goals." ON public.goals FOR ALL USING (auth.uid() = user_id);

-- 4. Create the Study Sessions table (Generated by Gemini)
CREATE TABLE public.study_sessions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
  goal_id UUID REFERENCES public.goals(id) ON DELETE CASCADE NOT NULL,
  title TEXT NOT NULL,
  scheduled_date TIMESTAMP WITH TIME ZONE NOT NULL,
  duration_minutes INTEGER DEFAULT 60,
  status session_status DEFAULT 'pending',
  mechanic mechanic_type DEFAULT 'theory',
  content_payload JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);

ALTER TABLE public.study_sessions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can manage their own study sessions." ON public.study_sessions FOR ALL USING (auth.uid() = user_id);

-- 5. Set up Storage Bucket for Syllabus Uploads
-- Run this to create the bucket (or create it manually in UI)
INSERT INTO storage.buckets (id, name, public) VALUES ('syllabus', 'syllabus', true) ON CONFLICT DO NOTHING;

-- Set up RLS for Storage
CREATE POLICY "Users can upload their own syllabus" 
ON storage.objects FOR INSERT 
WITH CHECK (bucket_id = 'syllabus' AND auth.uid()::text = (storage.foldername(name))[1]);

CREATE POLICY "Users can view their own syllabus" 
ON storage.objects FOR SELECT 
USING (bucket_id = 'syllabus' AND auth.uid()::text = (storage.foldername(name))[1]);
